### ISSUE TITLE
The link in Readme under SEIMS/knowledge is faulty

### ISSUE THREAD

**Issue by muhammedyusuf-sermet** [lreis2415/SEIMS#56]
(https://github.com/lreis2415/SEIMS/knowledge)

I would advise the use of relative paths

**Comment by crazyzlj** [comment]
> (https://github.com/lreis2415/SEIMS/knowledge)
> 
> I would advise the use of relative paths

Thanks and sorry for the delayed reply.
The README.md under SEIMS/knowledge has been updated.
All links in Jiang et al., (2019) follows the format like https://github.com/lreis2415/SEIMS/tree/master/knowledge.
